export const UPDATE_POSTS = "UPDATE_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_POST = "ADD_POST";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const ISAUTHENTICATED = "ISAUTHENTICATED";

export const SET_CURRENT_COMMENT = "SET_CURRENT_COMMENT"; 
export const ADD_COMMENT = "ADD_COMMENT"; 


